// 30 curated agricultural regions worldwide.
// Each region uses a bounding box MultiPolygon (PLAN.md fallback) for fast demo.
// bbox = [minLng, minLat, maxLng, maxLat]

export type RegionSeed = {
  name: string;
  country: string;
  bbox: [number, number, number, number];
  soil_type: 'loam' | 'clay' | 'sand' | 'silt' | 'peat' | 'chernozem';
  climate_zone:
    | 'temperate'
    | 'tropical'
    | 'arid'
    | 'continental'
    | 'mediterranean';
  avg_slope_deg: number;
  avg_elevation_m: number;
  avg_temp_c: number;
  annual_rainfall_mm: number;
  primary_crops: string[];
  area_ha: number;
};

export const REGIONS: RegionSeed[] = [
  // North America
  {
    name: 'Iowa, USA',
    country: 'USA',
    bbox: [-96.6, 40.4, -90.1, 43.5],
    soil_type: 'loam',
    climate_zone: 'continental',
    avg_slope_deg: 2,
    avg_elevation_m: 335,
    avg_temp_c: 9,
    annual_rainfall_mm: 870,
    primary_crops: ['corn', 'soy'],
    area_ha: 14_500_000,
  },
  {
    name: 'Nebraska, USA',
    country: 'USA',
    bbox: [-104.0, 40.0, -95.3, 43.0],
    soil_type: 'loam',
    climate_zone: 'continental',
    avg_slope_deg: 2,
    avg_elevation_m: 790,
    avg_temp_c: 10,
    annual_rainfall_mm: 600,
    primary_crops: ['corn', 'soy', 'wheat'],
    area_ha: 18_000_000,
  },
  {
    name: 'Kansas, USA',
    country: 'USA',
    bbox: [-102.0, 37.0, -94.6, 40.0],
    soil_type: 'loam',
    climate_zone: 'continental',
    avg_slope_deg: 1,
    avg_elevation_m: 610,
    avg_temp_c: 13,
    annual_rainfall_mm: 730,
    primary_crops: ['wheat', 'corn'],
    area_ha: 18_900_000,
  },
  {
    name: 'California Central Valley, USA',
    country: 'USA',
    bbox: [-122.0, 35.0, -119.0, 39.5],
    soil_type: 'silt',
    climate_zone: 'mediterranean',
    avg_slope_deg: 1,
    avg_elevation_m: 50,
    avg_temp_c: 17,
    annual_rainfall_mm: 380,
    primary_crops: ['almond', 'grape', 'tomato'],
    area_ha: 5_200_000,
  },
  {
    name: 'Saskatchewan, Canada',
    country: 'Canada',
    bbox: [-110.0, 49.0, -101.5, 54.0],
    soil_type: 'chernozem',
    climate_zone: 'continental',
    avg_slope_deg: 1,
    avg_elevation_m: 580,
    avg_temp_c: 3,
    annual_rainfall_mm: 400,
    primary_crops: ['wheat', 'canola'],
    area_ha: 26_000_000,
  },
  {
    name: 'Manitoba, Canada',
    country: 'Canada',
    bbox: [-101.5, 49.0, -95.0, 53.5],
    soil_type: 'chernozem',
    climate_zone: 'continental',
    avg_slope_deg: 1,
    avg_elevation_m: 230,
    avg_temp_c: 3,
    annual_rainfall_mm: 500,
    primary_crops: ['wheat', 'canola', 'soy'],
    area_ha: 7_500_000,
  },
  {
    name: 'Bajío, Mexico',
    country: 'Mexico',
    bbox: [-102.0, 20.0, -100.0, 21.5],
    soil_type: 'loam',
    climate_zone: 'arid',
    avg_slope_deg: 3,
    avg_elevation_m: 1800,
    avg_temp_c: 19,
    annual_rainfall_mm: 650,
    primary_crops: ['corn', 'sorghum', 'wheat'],
    area_ha: 1_200_000,
  },

  // South America
  {
    name: 'Mato Grosso, Brazil',
    country: 'Brazil',
    bbox: [-58.0, -16.0, -52.0, -10.0],
    soil_type: 'clay',
    climate_zone: 'tropical',
    avg_slope_deg: 3,
    avg_elevation_m: 400,
    avg_temp_c: 25,
    annual_rainfall_mm: 1800,
    primary_crops: ['soy', 'corn', 'cotton'],
    area_ha: 24_000_000,
  },
  {
    name: 'Pampas, Argentina',
    country: 'Argentina',
    bbox: [-63.0, -38.0, -58.0, -33.0],
    soil_type: 'loam',
    climate_zone: 'temperate',
    avg_slope_deg: 1,
    avg_elevation_m: 100,
    avg_temp_c: 16,
    annual_rainfall_mm: 900,
    primary_crops: ['soy', 'wheat', 'corn', 'beef'],
    area_ha: 50_000_000,
  },
  {
    name: 'Cauca Valley, Colombia',
    country: 'Colombia',
    bbox: [-76.5, 3.0, -75.5, 4.5],
    soil_type: 'loam',
    climate_zone: 'tropical',
    avg_slope_deg: 4,
    avg_elevation_m: 1000,
    avg_temp_c: 24,
    annual_rainfall_mm: 1100,
    primary_crops: ['sugarcane', 'coffee'],
    area_ha: 420_000,
  },

  // Europe
  {
    name: 'Île-de-France, France',
    country: 'France',
    bbox: [1.4, 48.1, 3.4, 49.2],
    soil_type: 'silt',
    climate_zone: 'temperate',
    avg_slope_deg: 2,
    avg_elevation_m: 100,
    avg_temp_c: 11,
    annual_rainfall_mm: 650,
    primary_crops: ['wheat', 'sugar beet'],
    area_ha: 570_000,
  },
  {
    name: 'Po Valley, Italy',
    country: 'Italy',
    bbox: [7.5, 44.5, 12.5, 45.7],
    soil_type: 'loam',
    climate_zone: 'temperate',
    avg_slope_deg: 1,
    avg_elevation_m: 80,
    avg_temp_c: 13,
    annual_rainfall_mm: 800,
    primary_crops: ['rice', 'corn', 'wheat'],
    area_ha: 4_600_000,
  },
  {
    name: 'Andalusia, Spain',
    country: 'Spain',
    bbox: [-7.5, 36.0, -1.5, 38.5],
    soil_type: 'clay',
    climate_zone: 'mediterranean',
    avg_slope_deg: 6,
    avg_elevation_m: 350,
    avg_temp_c: 18,
    annual_rainfall_mm: 550,
    primary_crops: ['olive', 'wheat', 'sunflower'],
    area_ha: 8_700_000,
  },
  {
    name: 'Bavaria, Germany',
    country: 'Germany',
    bbox: [9.5, 47.4, 13.8, 50.2],
    soil_type: 'loam',
    climate_zone: 'temperate',
    avg_slope_deg: 4,
    avg_elevation_m: 500,
    avg_temp_c: 8,
    annual_rainfall_mm: 950,
    primary_crops: ['wheat', 'barley', 'potato'],
    area_ha: 7_000_000,
  },
  {
    name: 'Wielkopolska, Poland',
    country: 'Poland',
    bbox: [15.5, 51.5, 18.5, 53.0],
    soil_type: 'loam',
    climate_zone: 'continental',
    avg_slope_deg: 1,
    avg_elevation_m: 100,
    avg_temp_c: 9,
    annual_rainfall_mm: 550,
    primary_crops: ['wheat', 'rye', 'potato'],
    area_ha: 3_000_000,
  },

  // Eastern Europe / Central Asia
  {
    name: 'Ukraine Chernozem Belt',
    country: 'Ukraine',
    bbox: [27.0, 46.5, 38.0, 50.5],
    soil_type: 'chernozem',
    climate_zone: 'continental',
    avg_slope_deg: 2,
    avg_elevation_m: 200,
    avg_temp_c: 9,
    annual_rainfall_mm: 550,
    primary_crops: ['wheat', 'sunflower', 'corn'],
    area_ha: 32_000_000,
  },
  {
    name: 'Krasnodar Krai, Russia',
    country: 'Russia',
    bbox: [37.0, 44.0, 41.5, 46.5],
    soil_type: 'chernozem',
    climate_zone: 'temperate',
    avg_slope_deg: 2,
    avg_elevation_m: 120,
    avg_temp_c: 12,
    annual_rainfall_mm: 700,
    primary_crops: ['wheat', 'sugar beet', 'sunflower'],
    area_ha: 4_000_000,
  },
  {
    name: 'Kazakhstan Steppe',
    country: 'Kazakhstan',
    bbox: [60.0, 49.0, 76.0, 54.0],
    soil_type: 'chernozem',
    climate_zone: 'continental',
    avg_slope_deg: 1,
    avg_elevation_m: 300,
    avg_temp_c: 4,
    annual_rainfall_mm: 350,
    primary_crops: ['wheat', 'barley'],
    area_ha: 23_000_000,
  },

  // Asia
  {
    name: 'Punjab, India',
    country: 'India',
    bbox: [73.5, 29.5, 76.8, 32.5],
    soil_type: 'loam',
    climate_zone: 'arid',
    avg_slope_deg: 1,
    avg_elevation_m: 220,
    avg_temp_c: 24,
    annual_rainfall_mm: 600,
    primary_crops: ['wheat', 'rice', 'cotton'],
    area_ha: 4_200_000,
  },
  {
    name: 'Punjab, Pakistan',
    country: 'Pakistan',
    bbox: [70.0, 28.5, 75.0, 33.5],
    soil_type: 'loam',
    climate_zone: 'arid',
    avg_slope_deg: 1,
    avg_elevation_m: 200,
    avg_temp_c: 25,
    annual_rainfall_mm: 500,
    primary_crops: ['wheat', 'cotton', 'rice'],
    area_ha: 12_000_000,
  },
  {
    name: 'Hokkaido, Japan',
    country: 'Japan',
    bbox: [139.5, 41.5, 145.5, 45.5],
    soil_type: 'loam',
    climate_zone: 'continental',
    avg_slope_deg: 5,
    avg_elevation_m: 250,
    avg_temp_c: 7,
    annual_rainfall_mm: 1100,
    primary_crops: ['rice', 'potato', 'wheat'],
    area_ha: 1_140_000,
  },
  {
    name: 'Heilongjiang, China',
    country: 'China',
    bbox: [121.0, 43.5, 134.5, 53.5],
    soil_type: 'chernozem',
    climate_zone: 'continental',
    avg_slope_deg: 2,
    avg_elevation_m: 250,
    avg_temp_c: 3,
    annual_rainfall_mm: 550,
    primary_crops: ['soy', 'corn', 'rice'],
    area_ha: 11_900_000,
  },
  {
    name: 'Henan, China',
    country: 'China',
    bbox: [110.5, 31.5, 116.7, 36.5],
    soil_type: 'loam',
    climate_zone: 'temperate',
    avg_slope_deg: 2,
    avg_elevation_m: 250,
    avg_temp_c: 14,
    annual_rainfall_mm: 800,
    primary_crops: ['wheat', 'corn'],
    area_ha: 7_900_000,
  },
  {
    name: 'Mekong Delta, Vietnam',
    country: 'Vietnam',
    bbox: [104.5, 8.5, 107.0, 11.0],
    soil_type: 'clay',
    climate_zone: 'tropical',
    avg_slope_deg: 1,
    avg_elevation_m: 5,
    avg_temp_c: 27,
    annual_rainfall_mm: 1700,
    primary_crops: ['rice', 'fruit'],
    area_ha: 4_000_000,
  },
  {
    name: 'Java, Indonesia',
    country: 'Indonesia',
    bbox: [105.0, -8.8, 114.5, -6.0],
    soil_type: 'clay',
    climate_zone: 'tropical',
    avg_slope_deg: 8,
    avg_elevation_m: 300,
    avg_temp_c: 26,
    annual_rainfall_mm: 2000,
    primary_crops: ['rice', 'sugarcane', 'corn'],
    area_ha: 3_400_000,
  },
  {
    name: 'Central Thailand',
    country: 'Thailand',
    bbox: [99.5, 13.5, 102.0, 16.5],
    soil_type: 'clay',
    climate_zone: 'tropical',
    avg_slope_deg: 1,
    avg_elevation_m: 30,
    avg_temp_c: 28,
    annual_rainfall_mm: 1400,
    primary_crops: ['rice', 'sugarcane', 'cassava'],
    area_ha: 4_800_000,
  },

  // Africa
  {
    name: 'Nile Delta, Egypt',
    country: 'Egypt',
    bbox: [29.5, 30.0, 32.5, 31.6],
    soil_type: 'silt',
    climate_zone: 'arid',
    avg_slope_deg: 1,
    avg_elevation_m: 10,
    avg_temp_c: 21,
    annual_rainfall_mm: 100,
    primary_crops: ['cotton', 'rice', 'wheat'],
    area_ha: 2_400_000,
  },
  {
    name: 'Ethiopian Highlands',
    country: 'Ethiopia',
    bbox: [36.5, 7.0, 41.0, 13.0],
    soil_type: 'clay',
    climate_zone: 'tropical',
    avg_slope_deg: 12,
    avg_elevation_m: 2200,
    avg_temp_c: 16,
    annual_rainfall_mm: 1100,
    primary_crops: ['teff', 'coffee', 'wheat'],
    area_ha: 7_500_000,
  },
  {
    name: 'KwaZulu-Natal, South Africa',
    country: 'South Africa',
    bbox: [29.0, -30.5, 32.5, -27.5],
    soil_type: 'clay',
    climate_zone: 'temperate',
    avg_slope_deg: 8,
    avg_elevation_m: 800,
    avg_temp_c: 18,
    annual_rainfall_mm: 950,
    primary_crops: ['sugarcane', 'corn'],
    area_ha: 1_800_000,
  },

  // Oceania
  {
    name: 'New South Wales, Australia',
    country: 'Australia',
    bbox: [141.0, -36.5, 152.5, -29.0],
    soil_type: 'loam',
    climate_zone: 'temperate',
    avg_slope_deg: 3,
    avg_elevation_m: 300,
    avg_temp_c: 17,
    annual_rainfall_mm: 600,
    primary_crops: ['wheat', 'cotton', 'beef'],
    area_ha: 22_000_000,
  },
  {
    name: 'Canterbury, New Zealand',
    country: 'New Zealand',
    bbox: [170.5, -44.5, 173.5, -42.5],
    soil_type: 'loam',
    climate_zone: 'temperate',
    avg_slope_deg: 4,
    avg_elevation_m: 300,
    avg_temp_c: 11,
    annual_rainfall_mm: 700,
    primary_crops: ['wheat', 'barley', 'dairy'],
    area_ha: 1_000_000,
  },
];

export function bboxToMultiPolygonGeoJSON(
  bbox: [number, number, number, number],
): {
  type: 'MultiPolygon';
  coordinates: [number, number][][][];
} {
  const [minLng, minLat, maxLng, maxLat] = bbox;
  return {
    type: 'MultiPolygon',
    coordinates: [
      [
        [
          [minLng, minLat],
          [maxLng, minLat],
          [maxLng, maxLat],
          [minLng, maxLat],
          [minLng, minLat],
        ],
      ],
    ],
  };
}
